language: nix
os:
  - linux

# Allow Emacs snapshot and integration builds to fail
matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot
    - env: EMACS_CI=emacs-26-3 INTEGRATION=yes

env:
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot
  - EMACS_CI=emacs-26-3 INTEGRATION=yes

install:
  # Install nix-emacs-ci
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

  # Install cask
  - nix-env -iA nixpkgs.cask

  # Install your dependencies
  - cask install

script:
  # Run the tests if we shouldn't trigger the integrations
  - if test -z "$INTEGRATION"; then make test;        fi

  # Otherwise we run the integration tests
  - if test -n "$INTEGRATION"; then make integration; fi
